### ISSUE TITLE
Make va-data-charlie repo public

### ISSUE THREAD

**Issue by OskarLiew** [vikinganalytics/va-data-charlie#1]
Required for documentation example

**Comment by tuix** [comment]
maybe it is better to avoid a submodule connection to another repo and have a copy of the data in mvg repo.

**Comment by OskarLiew** [comment]
I think it should be possible to run the examples without having to clone mvg repo. Ideally you should be able to just copy-paste the example code and get the same results.

But I am not sure what the best way to handle the data is. Perhaps it can be uploaded to an online data repository and downloaded in the script?

**Comment by tuix** [comment]
the data can be directly downloaded from GitHub too. We can have a download script to get it or have a zipped one pushed to the repo were people download and extract. Too many choices.

**Comment by OskarLiew** [comment]
@tuix I can't do this because I do not have admin privileges for this repo

**Comment by OskarLiew** [comment]
Now repo is public
